package io.thomasvitale.langchain4j.spring.openai.api.chat;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import io.thomasvitale.langchain4j.spring.openai.api.shared.Usage;

/**
 * Represents a chat completion response returned by model, based on the provided input.
 *
 * @param id A unique identifier for the chat completion.
 * @param choices A list of chat completion choices. Can be more than one if 'n' is greater than 1.
 * @param created The Unix timestamp (in seconds) of when the chat completion was created.
 * @param model The model used for the chat completion.
 * @param systemFingerprint This fingerprint represents the backend configuration that the model
 *                          runs with. Can be used in conjunction with the 'seed' request parameter
 *                          to understand when backend changes have been made that might impact
 *                          determinism.
 * @param object The object type, which is always 'chat.completion'.
 * @param usage Usage statistics for the completion request.
 *
 * @author Thomas Vitale
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public record ChatCompletionResponse(
        String id,
        List<Choice> choices,
        Long created,
        String model,
        String systemFingerprint,
        String object,
        Usage usage
) {
    /**
     * Chat completion choice.
     *
     * @param finishReason The reason the model stopped generating tokens.
     * @param index The index of the choice in the list of choices.
     * @param message A chat completion message generated by the model.
     * @param logprobs Log probability information for the choice.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    public record Choice(
            ChatCompletionFinishReason finishReason,
            Integer index,
            ChatCompletionMessage message,
            LogProbs logprobs
    ) {}

}
